### ISSUE TITLE
using container dpoloyments type and container exit due to error in "start_cerberus.py"

### ISSUE THREAD

**Issue by abhiroopghatak** [cloud-bulldozer/cerberus#139]
I'm using cerberus for openshift and tried deploying it as separate docker container outside of cluster:

Error:
File "start_cerberus.py", line 109, in main
    cluster_version = runcommand.invoke("kubectl get clusterversion")

==============complete log ==============

$docker logs -f cerberus
2021-05-08 09:08:38,893 [INFO] Starting ceberus
2021-05-08 09:08:38,904 [INFO] Initializing client to talk to the Kubernetes cluster
2021-05-08 09:08:38,986 [INFO] Fetching cluster info
error: the server doesn't have a resource type "clusterversion"
               _
  ___ ___ _ __| |__   ___ _ __ _   _ ___
 / __/ _ \ '__| '_ \ / _ \ '__| | | / __|
| (_|  __/ |  | |_) |  __/ |  | |_| \__ \
 \___\___|_|  |_.__/ \___|_|   \__,_|___/

2021-05-08 09:08:39,187 [ERROR] Failed to run kubectl get clusterversion
Traceback (most recent call last):
  File "start_cerberus.py", line 480, in <module>
    main(options.cfg)
  File "start_cerberus.py", line 109, in main
    cluster_version = runcommand.invoke("kubectl get clusterversion")
  File "/root/cerberus/cerberus/invoke/command.py", line 12, in invoke
    return output
UnboundLocalError: local variable 'output' referenced before assignment

**Comment by abhiroopghatak** [comment]
One issue with clusterversion  "cloud-bulldozer/cerberus/issues/133" is already in discussion thus closing this one as duplicate.
